# Generated by Django 4.2.13 on 2024-06-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_friends_friendsrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendsrequest',
            unique_together={('sent_from', 'sent_to')},
        ),
    ]
